#!/bin/bash

set -e

DOTDIR="$HOME/dotfiles/"
backup() {
    local appname="$1"
    local backuptheme="$2"
    local configdir="$HOME/.config/${appname}"
    local time=$(date +%Y%m%d%H%M%S)
    local selected="${DOTDIR}/${appname}"
    # Paranoic checks
    if [ ! -d "$selected" ]; then
        echo "Selected app config doesn't exist in the $DOTDIR folder!"
        exit 1
    else
        echo "$selected found..."
    fi
    if [ ! -d "${selected}/${backuptheme}" ]; then
        echo "Selected app config doesn't exist in the $DOTDIR folder!"
        exit 1
    else
        echo "$backuptheme theme found..."
    fi    
    
    if [ ! -e "$configdir" ]; then
       echo "No previous config for $appname found."
       echo "Skipping backup creation"
    else 
        echo "Found existing config directory."
        local response=$(printf "Yes\nNo" | fzf --prompt="Create a backup?" --height="20%")
        case $response in 
            "Yes")
                mv "$configdir" "${configdir}_backup_${time}"
                ;;
            "No")
                rm -fr "$configdir"
                ;;
            *)
                echo "Aborted. Exiting..."
                exit 1
                ;;
        esac 
    fi
}
apply_theme() {
    local app="$1"
    local theme="$2"
    local target="$HOME/.config"
    local final="${target}/${1}"
    echo "Applying ${2} theme for ${1} to path ${final}..."
    ln -s "${DOTDIR}/${app}/${theme}" "$final"
    echo "Done!"
}

CHOOSENTHEME=$(ls ${DOTDIR}/themes | fzf --prompt="Choose the theme..." --height="20%")
for stage in $(find $HOME/dotfiles -maxdepth 1 -mindepth 1 -type d); do
    foundpath=$(find $stage -maxdepth 1 -mindepth 1 -type d -name "${CHOOSENTHEME}")
    if [ -n "$foundpath" ]; then
        targetapp=$(basename "${stage}")
        backup "$targetapp" "$CHOOSENTHEME"
        apply_theme "$targetapp" "$CHOOSENTHEME"
    fi 
done 
